version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - mysql_db

  web:
      build:
        context: . 
        dockerfile: web/Dockerfile.web 
      env_file:
        - .env
      ports:
        - "8000:8000"
      volumes:
        - ./web:/app 
        - ./database:/app/database 
      restart: unless-stopped
      depends_on:
        - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: super_root_password123
      MYSQL_DATABASE: proxy_bot_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: super_password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: