version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres_db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: super_password123
      POSTGRES_DB: proxy_bot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: